Controllers/EntertainmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using PFD_SaveTheEnvironment.DAL;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace PFD_SaveTheEnvironment.Controllers
{
    public class EntertainmentController : Controller
    {
        private UsersDAL userContext = new UsersDAL();
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult FlappyEarth()
        {
            return View();
        }

        public IActionResult dinoGame()
        {

            return View();
        }

        public IActionResult HangMan()
        {
            return View();
        }
        public IActionResult pointRedemption()
        {
            return View();
        }

        public ActionResult AddPointsDino(int id)
        {
            if (HttpContext.Session.GetString("LoginID") != null && HttpContext.Session.GetString("Role") == "User")
            {
                userContext.AddGamePoint(HttpContext.Session.GetString("LoginID"), id);
            }
            return RedirectToAction("dinoGame");
        }
        public ActionResult AddPointsGravit(int id)
        {
            if (HttpContext.Session.GetString("LoginID") != null && HttpContext.Session.GetString("Role") == "User")
            {
                userContext.AddGamePoint(HttpContext.Session.GetString("LoginID"), id);
            }
            return RedirectToAction("FlappyEarth");
        }
        public ActionResult AddPointsHang()
        {
            if (HttpContext.Session.GetString("LoginID") != null && HttpContext.Session.GetString("Role") == "User")
            {
                userContext.AddGamePoint(HttpContext.Session.GetString("LoginID"), 25);
            }
            return RedirectToAction("HangMan");
        }
    }
}

Views/Entertainment/FlappyEarth.cshtml
@{
    ViewData["Title"] = "FlappyEarth!";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        canvas {
            padding-left: 0;
            padding-right: 0;
            margin-left: auto;
            margin-right: auto;
            border: 1px solid #d3d3d3;
            display: block;
            background-color: #d3d3d3;
        }

        .container {
            height: 200px;
            position: relative;
        }

        .center {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            text-align:center;
        }

        .theButton {
            margin-top: 55px;
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 26px;
        }

        @@media screen and (max-width: 1200px) {
            .theButton {
                margin-top: 75px;
            }
        }

        @@media screen and (max-width: 1000px) {
            .theButton {
                margin-top: 95px;
            }
        }

        @@media screen and (max-width: 990px) {
            .theButton {
                margin-top: 159px;
            }
        }

        @@media screen and (max-width: 540px) {
            .theButton {
                margin-top: 190px;
            }
        }

        @@media screen and (max-width: 519px) {
            .theButton {
                margin-top: 240px;
            }
        }

        @@media screen and (max-width: 429px) {
            .theButton {
                margin-top: 290px;
            }
        }

        @@media screen and (max-width: 385px) {
            .theButton {
                margin-top: 345px;
            }
        }

    </style>
</head>
<body onload="startGame()">
    <br />
    <div class="container ">
        <div class="center">
            <script src="~/js/wasdGame.js" type="text/javascript"></script>
            <p>The earth is under attack by non-environmental friendly companies!</p>
            <p>Click Gravitate to avoid annihilation!</p>
            <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onmousedown="accelerate(-0.2)" onmouseup="accelerate(0.05)">Gravitate</button>
        </div>
    </div>
</body>

</html>

Views/Entertainment/Games.cshtml
@{
    ViewData["Title"] = "Games";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        canvas {
            padding-left: 0;
            padding-right: 0;
            margin-left: auto;
            margin-right: auto;
            border: 1px solid #d3d3d3;
            display: block;
            background-color: #f1f1f1;
        }

        .container {
            height: 200px;
            position: relative;
        }

        .center {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            text-align:center;
        }
    </style>
</head>
<body onload="startGame()">
    <br>
    <div class="container ">
        <div class="center">
            <script src="~/js/wasdGame.js" type="text/javascript"></script>
            <button onmousedown="accelerate(-0.2)" onmouseup="accelerate(0.05)">Gravitate</button>
            <p>The earth is under attack by non-environmental friendly companies!</p>
            <p>Click Gravitate to avoid annihilation!</p>
            <br />
            <p>Earth logo by <a href="https://www.flaticon.com/authors/freepik" target="_blank">Visit freepik!</a> </p>
        </div>
    </div>
</body>

</html>

Views/Entertainment/HangMan.cshtml
@{
    ViewData["Title"] = "Hang Man";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <div class="float-right">Wrong Guesses: <span id='mistakes'>0</span> of <span id='maxWrong'></span></div>
        <div class="text-center">
            <img id='hangmanPic' src="~/images/0.jpg" alt="">
            <p id="typeComp">Guess the Car Company:</p>
            <p id="wordSpotlight">The word to be guessed goes here</p>
            <div id="keyboard" class="font-weight-bold"></div>
            <br />
            <button class="btn btn-info" id="resetBtn" onClick="reset()">Reset</button>
        </div>
    </div>
    <script src="~/js/hangman.js"></script>
</body>
</html>

Views/Entertainment/Index.cshtml
@{
    ViewData["Title"] = "Games";
}

<!DOCTYPE HTML>
<style>
    .button {
        display: inline-block;
        padding: 3px 5px;
        border: 1px solid #000;
        background: #eee;
        font-size: 200%;
    }

    @@media screen and (max-width: 600px) {
        .text-center {
            margin-left:auto;
            margin-right:auto;
        }
    }
</style>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <br>
    <h1 class="font-weight-bold text-center">PolyEarth Games</h1>
    <hr />
    <br />
    <div class="row">
        <div class="col-lg-1 col-sm"></div>
        <a href="~/Entertainment/dinoGame" class="text-center">
            <img src="~/images/GravitEarth.png" alt="GravitEarth" width="325" height="325" class="mx-auto d-block" />
        </a>
        <br />
        <div class="col-lg-1 col-sm"></div>
        <div class="col-lg-5 col-md-5 col-sm-12 text-center">
            <h3>GravitEarth</h3>
            <br />
            <p>
                Play GravitEarth on our website where you navigate the Earth through various obstacles that threaten its destruction!
            </p>
            <br />
            <div class="text-center">
                <a class="btn btn-primary text-white rounded-pill mr-2" asp-action="FlappyEarth" asp-controller="Entertainment">Play</a>
            </div>
        </div>
    </div>
    <br />
    <hr />
    <br />
    <div class="row">
        <div class="col-lg-1 col-sm"></div>
        <a href="~/Entertainment/dinoGame" class="text-center">
            <img src="~/images/EarthJump.png" alt="EarthJump" width="325" height="325" class="mx-auto d-block" />
        </a>
        <br />
        <div class="col-lg-1 col-sm"></div>
        <div class="col-lg-5 col-md-5 col-sm-12 text-center">
            <h3>EarthJump!</h3>
            <br />
            <p>
                Play EarthJump! on our website where you play as the Earth and need to hop over the many obstacles that stand in your way!
            </p>
            <br />
            <div class="text-center">
                <a class="btn btn-primary text-white rounded-pill mr-2" asp-action="dinoGame" asp-controller="Entertainment">Play</a>
            </div>
        </div>
    </div>
    <br />
    <hr />
    <br />
    <div class="row">
        <div class="col-lg-1 col-sm"></div>
        <a href="~/Entertainment/HangMan" class="text-center">
            <img src="~/images/HangEarth.png" alt="HangEarth" width="325" height="325" class="mx-auto d-block" />
        </a>
        <br />
        <div class="col-lg-1 col-sm"></div>
        <div class="col-lg-5 col-md-5 col-sm-12 text-center">
            <h3>HangEarth</h3>
            <br />
            <p>
                Solve the hidden word based on a good or bad company based on their Environmental Impact to save the Earth from being hung!
            </p>
            <br />
            <div class="text-center">
                <a class="btn btn-primary text-white rounded-pill mr-2" asp-action="HangMan" asp-controller="Entertainment">Play</a>
            </div>
        </div>
    </div>
    <br />
    <hr />
    <br />
    <div class="text-center">
        <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onclick="showCredits()" id="creditsButton">Hide Credits</button>
        <br />
        <div id="gameCredits" class="gameCredits">
            <br />
            <p>Earth logo by <a href="https://www.flaticon.com/authors/freepik" target="_blank">Visit freepik!</a> </p>
            <div> Nestle icon made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
            <div> Coca Cola Icon made by <a href="https://www.flaticon.com/authors/smalllikeart" title="smalllikeart">smalllikeart</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
            <div> Pepsi Icon made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
            <div> Vistra Icon made in Microsoft Powerpoint, Company: <a href="https://www.vistracorp.com/" title="Flaticon">Vistra Energies</a></div>
            <div> LYB Icon made in Microsoft Powerpoint, Company: <a href="https://www.lyondellbasell.com/" title="Flaticon">LyondellBasell</a></div>
            <br />
            <div> GravitEarth and EarthJump referred from <a href="https://www.w3schools.com/graphics/game_intro.asp" title="Freepik">W3Schools</a></div>
            <br />
            <div> List of polluters based on different categories <a href="https://peri.umass.edu/greenhouse-100-polluters-index-current" title="Freepik">Political Economy Research Institute</a></div>
        </div>
    </div>
    <br />
    <script>
        function showCredits() {
            var gameCredits = document.getElementById("gameCredits");
            if (gameCredits.style.display === "none") {
                gameCredits.style.display = "block";
                document.getElementById("creditsButton").innerHTML = 'Hide Credits'
            } else {
                gameCredits.style.display = "none";
                document.getElementById("creditsButton").innerHTML = 'Show Credits'
            }
        }
    </script>
</body>
</html>

Views/Entertainment/dinoGame.cshtml
@{
    ViewData["Title"] = "dinoGame!";
}

<!DOCTYPE HTML>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        canvas {
            padding-left: 0;
            padding-right: 0;
            margin-left: auto;
            margin-right: auto;
            border: 1px solid #d3d3d3;
            display: block;
            background-color: #f1f1f1;
        }

        .container {
            height: 200px;
            position: relative;
        }

        .center {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            text-align: center;
        }

        .theButton {
            margin-top: 55px;
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 26px;
        }

        @@media screen and (max-width: 1200px) {
            .theButton {
                margin-top: 75px;
            }
        }

        @@media screen and (max-width: 1000px) {
            .theButton {
                margin-top: 95px;
            }
        }

        @@media screen and (max-width: 990px) {
            .theButton {
                margin-top: 159px;
            }
        }

        @@media screen and (max-width: 540px) {
            .theButton {
                margin-top: 190px;
            }
        }

        @@media screen and (max-width: 519px) {
            .theButton {
                margin-top: 240px;
            }
        }

        @@media screen and (max-width: 429px) {
            .theButton {
                margin-top: 290px;
            }
        }

        @@media screen and (max-width: 385px) {
            .theButton {
                margin-top: 345px;
            }
        }
    </style>
</head>
<body onload="startGame()">
    <br />
    <div class="container">
        <div class="center">
            <script src="~/js/dinoGame.js" type="text/javascript"></script>
            <p>The earth is soon to be under collision with environmentally harming companies! Avoid them at all costs by jumping!</p>
            <p>Click jump to avoid annihilation!</p>
            <button type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off" onmousedown="accelerate(-0.15)" onmouseup="accelerate(0.15)">Jump!</button>
        </div>
    </div>
</body>

</html>

Views/Entertainment/pointRedemption.cshtml
@{
    ViewData["Title"] = "PointRedemption";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width,
                                           initial-scale = 1" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>


<body>
    <h1>Point Redemption</h1>
    <div class="container d-flex flex-wrap">

        <div class="card col-3 m-3 p-0">
            <button href="" style="text-decoration:none">
                <div class="container">
                    <h4 class="text-nowrap"><b>Icon Frame</b></h4>
                    <h5>cost: 500</h5>
                    <img src="~/images/frame1.png" alt="frame1" style="width:100%">
                    @*https://www.pngkit.com/png/full/66-667623_level-1-summoner-icon-border-league-of-legends.png*@
                    <h4><b>Redeem</b></h4>
                </div>
            </button>
        </div>

        <div class="card  col-3 m-3 p-0">
            <button href="" style="text-decoration:none">
                <div class="container">
                    <h4 class="text-nowrap"><b>Icon Frame</b></h4>
                    <h5>cost: 1000</h5>
                    <img src="~/images/frame2.png" alt="frame2" style="width:100%">
                    @* https://www.nicepng.com/png/full/14-146964_level-300-summoner-icon-border-poker.png *@
                    <h4><b>Redeem</b></h4>

                </div>
            </button>
        </div>

        <div class="card col-3 m-3 p-0">
            <button href="" style="text-decoration:none">
                <div class="container">
                    <h4 class="text-nowrap"><b>Icon Frame</b></h4>
                    <h5>cost: 2500</h5>
                    <img src="~/images/frame3.png" alt="frame3" style="width:100%">
                    @*https://www.pngkit.com/png/full/172-1726769_level-150-summoner-icon-border-level-150-league.png*@
                    <h4><b>Redeem</b></h4>
                </div>
            </button>
        </div>

        <div class="card col-3 m-3 p-0">
            <button href="" style="text-decoration:none">
                <div class="container">
                    <h4 class="text-nowrap"><b>Icon Frame</b></h4>
                    <h5>cost: 5000</h5>
                    <img src="~/images/frame4.png" alt="frame4" style="width:100%">
                    @*https://www.seekpng.com/png/full/66-667318_level-225-summoner-icon-border-league-of-legends.png*@
                    <h4><b>Redeem</b></h4>
                </div>
            </button>
        </div>
    </div>
    </div>

</body>

</html>